<a href="https://colab.research.google.com/github/sthory2345/dsmp_tasks/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### `Task` How dimensionality reduction using Principal Component Analysis (PCA) on the Wine Quality dataset contributes to improving the classification accuracy and efficiency of wine type.

Note : Use KNN for Classification.

Data Link :  [Wine Data](https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv)

In [2]:
# Data Loading
import pandas as pd
wine_data_path = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv"
df = pd.read_csv(wine_data_path)
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [23]:
df.sample(5)

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
795   white            7.2              0.31         0.26             7.3   
2245  white            7.5              0.31         0.24             7.1   
5136    red            7.2              0.63         0.00             1.9   
5978    red           10.3              0.27         0.56             1.4   
5482    red           11.8              0.33         0.49             3.4   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
795       0.050                 37.0                 157.0  0.99625  3.09   
2245      0.031                 28.0                 141.0  0.99397  3.16   
5136      0.097                 14.0                  38.0  0.99675  3.37   
5978      0.047                  3.0                   8.0  0.99471  3.16   
5482      0.093                 54.0                  80.0  1.00020  3.30   

      sulphates  alcohol  quality  
795        0.43      9.0        5  
2245       0.38     10.6        7  
5136       0.58      9.0        6  
5978       0.51     11.8        6  
5482       0.76     10.7        7

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [3]:
df.shape

(6497, 13)

In [5]:
df.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(1168)

In [27]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.shape

(5295, 13)

In [28]:
from sklearn.model_selection import train_test_split
X = df.drop('type',axis=1)
y = df['type']
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size= 0.2 , random_state = 45)

In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(X_train)
scaler.transform(X_test)

array([[ 0.28255799,  7.36726531, -2.15246294, ..., -0.89411002,
         0.2984423 , -3.20129589],
       [ 1.64907335, -1.09608386, -0.6037807 , ..., -1.41662503,
        -0.88804971, -0.90909011],
       [ 0.58622807, -0.55967441, -0.40177867, ...,  0.21623438,
        -1.56604515,  0.23701278],
       ...,
       [ 2.40824856,  1.58596341,  1.14690357, ...,  0.60812063,
        -1.82029343, -3.20129589],
       [-0.4006997 , -0.50007336,  1.28157159, ..., -0.24096626,
        -0.80330028, -0.90909011],
       [ 1.34540327, -1.03648281,  1.14690357, ..., -0.17565188,
        -0.04055542,  1.38311567]])

In [34]:
cov_matrix = X_train.cov()

In [39]:
import numpy as np
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvectors

array([[-7.63672155e-03, -5.50006677e-03, -3.04369672e-02,
         7.06761020e-01,  7.01152248e-01, -4.56166406e-02,
         3.34822390e-02, -3.29966401e-02,  4.93659268e-02,
        -3.35861347e-02, -1.61961510e-03,  1.02099774e-03],
       [-1.15682932e-03, -9.37581887e-04, -2.21599446e-03,
         2.53062074e-02, -1.84689354e-02, -3.95836892e-02,
         6.56387494e-01, -2.89262749e-01, -3.82835643e-01,
         5.75654256e-01,  7.05760612e-02,  2.25511536e-03],
       [ 4.59990602e-04, -2.25612374e-04, -2.36609688e-03,
         2.30364034e-02,  5.24949638e-02,  8.40114612e-03,
        -4.33228021e-01,  4.68632412e-01,  5.92284374e-02,
         7.63492800e-01,  5.38979829e-02,  2.26997052e-04],
       [ 3.77395517e-02,  1.97874272e-02, -9.96131624e-01,
        -6.85075429e-02,  2.44502955e-02, -2.38210340e-02,
         4.25131424e-03,  3.54404640e-03,  3.20354379e-03,
        -2.41514394e-03, -7.42427011e-04,  3.85044473e-04],
       [-1.76169284e-04,  1.02934739e-04, -1.4496921

In [38]:
eigenvalues


array([3.41066372e+03, 1.40627575e+02, 1.56170959e+01, 1.78868171e+00,
       1.26787708e+00, 4.63778191e-01, 3.14925788e-02, 2.08502150e-02,
       1.52355555e-02, 1.06764966e-02, 8.69841395e-04, 6.03062618e-07])

In [50]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [46]:
X_train.shape

(4236, 12)

In [51]:
X_train_pca.shape

(4236, 5)

In [54]:
X_test.shape

(1059, 12)

In [52]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_pca, y_train)
knn.score(X_test_pca, y_test)

0.9338999055712937

In [49]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.9386213408876298